### ISSUE TITLE
Missing Attribute Editor Features

### ISSUE THREAD

**Issue by Pirminus** [Autodesk/maya-usd#473]
Hi Dev-Team,

whenever I select an USD object in the outline I'm missing all the USD-specific attributes in the Attribute Editor.

I have seen that there should be at last some transformation information about the selected prims like in this gif

https://user-images.githubusercontent.com/3026529/78174149-cae7f580-7426-11ea-9da3-99546559e4c1.gif

Selecting the top-most object in the Kitchen-Set-hierarchy gives me all the standard maya attributes.
Selecting the Shape gives me just standard shape-attributes.
Selecting any 'usd-prim' with the blue icon in the outliner shows absolutly nothing in the attribute editor.

**Steps to reproduce**
1. Open Maya
2. Create->Universial Scene Description ->Stage from exsisting Layer
3. Select the Kitchen_set.usd and load
4. select any object from the kitchen_usd file

**Expected behavior**

USD-specific attributes should be listed in the outliner.

**Attachments**
![usd_empty_attribute_editor](https://user-images.githubusercontent.com/32384165/80521674-b64a3f00-898b-11ea-89a6-eda0e4731a2f.JPG)
![usd_empty_attribute_editor_plugins](https://user-images.githubusercontent.com/32384165/80521766-dd087580-898b-11ea-89c8-051667f054a9.JPG)

**Specs (if applicable):**
 - Windows 10
 - Maya version 2020
 - Maya USD release 0.1.0

**Comment by seando-adsk** [comment]
@Pirminus thank you for reaching out. Unfortunately, Maya 2020 doesn't have the required UFE version to support that functionality. V2 of UFE is required and that has only been implemented into the beta version of Maya. Maya 2018, 2019, and 2020 do not support that. If you would like, you can try out PR114 and it should be working there.

**Comment by olliRJL** [comment]
@seando-adsk what is the plan regarding the roll out of UFE v2 - can we expect that in some later Maya2020 update or Maya2021 earliest?

**Comment by wtelford** [comment]
Hey Olli,
UFEv2 is currently only available in the Maya Beta PR's. A feature-complete Maya USD premiere experience will require a current Maya USD plugin and a new release of Maya to support it. With that in place we will evaluate what workflows and functionality can reasonably be supported in current release versions of Maya and potential future updates.

**Comment by santosg87** [comment]
based on the above comment, I will go ahead and mark this one as closed - and if we change the plans or have anyhting in mind we can re-open this. :)

**Comment by spatulaG** [comment]
Hello, I am still not able to view attributes in maya 2022, wonder if there's a solution to that?:)
Rosy
